function [pos_hip,vel_hip] = func_hip(in1,in2)
%FUNC_HIP
%    [POS_HIP,VEL_HIP] = FUNC_HIP(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    27-Aug-2020 15:38:27

Rb_1_1 = in1(16,:);
Rb_1_2 = in1(19,:);
Rb_1_3 = in1(22,:);
Rb_2_1 = in1(17,:);
Rb_2_2 = in1(20,:);
Rb_2_3 = in1(23,:);
Rb_3_1 = in1(18,:);
Rb_3_2 = in1(21,:);
Rb_3_3 = in1(24,:);
lh_FL_1 = in2(9,:);
lh_FL_2 = in2(10,:);
lh_FL_3 = in2(11,:);
lh_HL_1 = in2(15,:);
lh_HL_2 = in2(16,:);
lh_HL_3 = in2(17,:);
lh_FR_1 = in2(6,:);
lh_FR_2 = in2(7,:);
lh_FR_3 = in2(8,:);
lh_HR_1 = in2(12,:);
lh_HR_2 = in2(13,:);
lh_HR_3 = in2(14,:);
vb_1 = in1(37,:);
vb_2 = in1(38,:);
vb_3 = in1(39,:);
wb_1 = in1(40,:);
wb_2 = in1(41,:);
wb_3 = in1(42,:);
xb_1 = in1(13,:);
xb_2 = in1(14,:);
xb_3 = in1(15,:);
pos_hip = [xb_1+Rb_1_1.*lh_FR_1+Rb_1_2.*lh_FR_2+Rb_1_3.*lh_FR_3;xb_2+Rb_2_1.*lh_FR_1+Rb_2_2.*lh_FR_2+Rb_2_3.*lh_FR_3;xb_3+Rb_3_1.*lh_FR_1+Rb_3_2.*lh_FR_2+Rb_3_3.*lh_FR_3;xb_1+Rb_1_1.*lh_FL_1+Rb_1_2.*lh_FL_2+Rb_1_3.*lh_FL_3;xb_2+Rb_2_1.*lh_FL_1+Rb_2_2.*lh_FL_2+Rb_2_3.*lh_FL_3;xb_3+Rb_3_1.*lh_FL_1+Rb_3_2.*lh_FL_2+Rb_3_3.*lh_FL_3;xb_1+Rb_1_1.*lh_HR_1+Rb_1_2.*lh_HR_2+Rb_1_3.*lh_HR_3;xb_2+Rb_2_1.*lh_HR_1+Rb_2_2.*lh_HR_2+Rb_2_3.*lh_HR_3;xb_3+Rb_3_1.*lh_HR_1+Rb_3_2.*lh_HR_2+Rb_3_3.*lh_HR_3;xb_1+Rb_1_1.*lh_HL_1+Rb_1_2.*lh_HL_2+Rb_1_3.*lh_HL_3;xb_2+Rb_2_1.*lh_HL_1+Rb_2_2.*lh_HL_2+Rb_2_3.*lh_HL_3;xb_3+Rb_3_1.*lh_HL_1+Rb_3_2.*lh_HL_2+Rb_3_3.*lh_HL_3];
if nargout > 1
    t2 = Rb_1_1.*wb_2;
    t3 = Rb_1_2.*wb_1;
    t4 = Rb_1_1.*wb_3;
    t5 = Rb_1_3.*wb_1;
    t6 = Rb_1_2.*wb_3;
    t7 = Rb_1_3.*wb_2;
    t8 = Rb_2_1.*wb_2;
    t9 = Rb_2_2.*wb_1;
    t10 = Rb_2_1.*wb_3;
    t11 = Rb_2_3.*wb_1;
    t12 = Rb_2_2.*wb_3;
    t13 = Rb_2_3.*wb_2;
    t14 = Rb_3_1.*wb_2;
    t15 = Rb_3_2.*wb_1;
    t16 = Rb_3_1.*wb_3;
    t17 = Rb_3_3.*wb_1;
    t18 = Rb_3_2.*wb_3;
    t19 = Rb_3_3.*wb_2;
    t20 = -t3;
    t21 = -t5;
    t22 = -t7;
    t23 = -t9;
    t24 = -t11;
    t25 = -t13;
    t26 = -t15;
    t27 = -t17;
    t28 = -t19;
    t29 = t2+t20;
    t30 = t4+t21;
    t31 = t6+t22;
    t32 = t8+t23;
    t33 = t10+t24;
    t34 = t12+t25;
    t35 = t14+t26;
    t36 = t16+t27;
    t37 = t18+t28;
    vel_hip = [vb_1+lh_FR_1.*t31-lh_FR_2.*t30+lh_FR_3.*t29;vb_2+lh_FR_1.*t34-lh_FR_2.*t33+lh_FR_3.*t32;vb_3+lh_FR_1.*t37-lh_FR_2.*t36+lh_FR_3.*t35;vb_1+lh_FL_1.*t31-lh_FL_2.*t30+lh_FL_3.*t29;vb_2+lh_FL_1.*t34-lh_FL_2.*t33+lh_FL_3.*t32;vb_3+lh_FL_1.*t37-lh_FL_2.*t36+lh_FL_3.*t35;vb_1+lh_HR_1.*t31-lh_HR_2.*t30+lh_HR_3.*t29;vb_2+lh_HR_1.*t34-lh_HR_2.*t33+lh_HR_3.*t32;vb_3+lh_HR_1.*t37-lh_HR_2.*t36+lh_HR_3.*t35;vb_1+lh_HL_1.*t31-lh_HL_2.*t30+lh_HL_3.*t29;vb_2+lh_HL_1.*t34-lh_HL_2.*t33+lh_HL_3.*t32;vb_3+lh_HL_1.*t37-lh_HL_2.*t36+lh_HL_3.*t35];
end
