function [J_FR,J_FL,J_HR,J_HL] = func_feet_end_Jacobians(in1,in2)
%FUNC_FEET_END_JACOBIANS
%    [J_FR,J_FL,J_HR,J_HL] = FUNC_FEET_END_JACOBIANS(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    28-Aug-2020 16:53:58

Rb_1_1 = in1(16,:);
Rb_1_2 = in1(19,:);
Rb_1_3 = in1(22,:);
Rb_2_1 = in1(17,:);
Rb_2_2 = in1(20,:);
Rb_2_3 = in1(23,:);
Rb_3_1 = in1(18,:);
Rb_3_2 = in1(21,:);
Rb_3_3 = in1(24,:);
qf_1 = in1(1,:);
qf_2 = in1(2,:);
qf_3 = in1(3,:);
qf_4 = in1(4,:);
qs_1 = in1(5,:);
qs_2 = in1(6,:);
qs_3 = in1(7,:);
qs_4 = in1(8,:);
t2 = cos(qf_1);
t3 = cos(qf_2);
t4 = cos(qf_3);
t5 = cos(qf_4);
t6 = cos(qs_1);
t7 = cos(qs_2);
t8 = cos(qs_3);
t9 = cos(qs_4);
t10 = sin(qf_1);
t11 = sin(qf_2);
t12 = sin(qf_3);
t13 = sin(qf_4);
t14 = sin(qs_1);
J_FR = reshape([Rb_1_1.*t6-Rb_1_3.*t2.*t14+Rb_1_2.*t10.*t14,Rb_2_1.*t6-Rb_2_3.*t2.*t14+Rb_2_2.*t10.*t14,Rb_3_1.*t6-Rb_3_3.*t2.*t14+Rb_3_2.*t10.*t14,Rb_1_2.*t2+Rb_1_3.*t10,Rb_2_2.*t2+Rb_2_3.*t10,Rb_3_2.*t2+Rb_3_3.*t10,-Rb_1_1.*t14-Rb_1_3.*t2.*t6+Rb_1_2.*t6.*t10,-Rb_2_1.*t14-Rb_2_3.*t2.*t6+Rb_2_2.*t6.*t10,-Rb_3_1.*t14-Rb_3_3.*t2.*t6+Rb_3_2.*t6.*t10],[3,3]);
if nargout > 1
    t15 = sin(qs_2);
    J_FL = reshape([Rb_1_1.*t7-Rb_1_3.*t3.*t15+Rb_1_2.*t11.*t15,Rb_2_1.*t7-Rb_2_3.*t3.*t15+Rb_2_2.*t11.*t15,Rb_3_1.*t7-Rb_3_3.*t3.*t15+Rb_3_2.*t11.*t15,Rb_1_2.*t3+Rb_1_3.*t11,Rb_2_2.*t3+Rb_2_3.*t11,Rb_3_2.*t3+Rb_3_3.*t11,-Rb_1_1.*t15-Rb_1_3.*t3.*t7+Rb_1_2.*t7.*t11,-Rb_2_1.*t15-Rb_2_3.*t3.*t7+Rb_2_2.*t7.*t11,-Rb_3_1.*t15-Rb_3_3.*t3.*t7+Rb_3_2.*t7.*t11],[3,3]);
end
if nargout > 2
    t16 = sin(qs_3);
    J_HR = reshape([Rb_1_1.*t8-Rb_1_3.*t4.*t16+Rb_1_2.*t12.*t16,Rb_2_1.*t8-Rb_2_3.*t4.*t16+Rb_2_2.*t12.*t16,Rb_3_1.*t8-Rb_3_3.*t4.*t16+Rb_3_2.*t12.*t16,Rb_1_2.*t4+Rb_1_3.*t12,Rb_2_2.*t4+Rb_2_3.*t12,Rb_3_2.*t4+Rb_3_3.*t12,-Rb_1_1.*t16-Rb_1_3.*t4.*t8+Rb_1_2.*t8.*t12,-Rb_2_1.*t16-Rb_2_3.*t4.*t8+Rb_2_2.*t8.*t12,-Rb_3_1.*t16-Rb_3_3.*t4.*t8+Rb_3_2.*t8.*t12],[3,3]);
end
if nargout > 3
    t17 = sin(qs_4);
    J_HL = reshape([Rb_1_1.*t9-Rb_1_3.*t5.*t17+Rb_1_2.*t13.*t17,Rb_2_1.*t9-Rb_2_3.*t5.*t17+Rb_2_2.*t13.*t17,Rb_3_1.*t9-Rb_3_3.*t5.*t17+Rb_3_2.*t13.*t17,Rb_1_2.*t5+Rb_1_3.*t13,Rb_2_2.*t5+Rb_2_3.*t13,Rb_3_2.*t5+Rb_3_3.*t13,-Rb_1_1.*t17-Rb_1_3.*t5.*t9+Rb_1_2.*t9.*t13,-Rb_2_1.*t17-Rb_2_3.*t5.*t9+Rb_2_2.*t9.*t13,-Rb_3_1.*t17-Rb_3_3.*t5.*t9+Rb_3_2.*t9.*t13],[3,3]);
end
